[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/x"
  to = "/y"
  status = 302

[[redirects]]
  from = "/y"
  to = "/z"
  status = 302

[[redirects]]
  from = "/z"
  to = "/netliheart.svg"
  status = 302
  force = true